version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    ports:
      - '9200:9200'
  kibana:
    container_name: kibana
    build: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
  fluentd:
    container_name: fluentd
    build: fluentd/
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
    depends_on:
      - elasticsearch
    ports:
      - '24224:24224'
  tomcat:
    image: tomcat:latest
    container_name: tomcat
    depends_on:
      - fluentd
    ports:
      - '8080:8080'
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: docker.{{.FullID}}
  nginx:
    container_name: nginx
    build: nginx/
    depends_on:
      - fluentd
    ports:
      - '80:80'
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: docker.{{.FullID}}
